# Copy or edit for your MySQL server. This file is copied to WEB-INF/classes at compile time.
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/unibook?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=root
db.password=
